apiVersion: v1
kind: Service
metadata:
  name: {{ include "board.fullname" . }}
  labels:
    {{- include "board.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      name: http
  selector:
    {{- include "board.selectorLabels" . | nindent 4 }}
